#!/usr/bin/perl -w
# perlcat - a less capable cat(1)
use Getopt::Std;

#these first two declarations are not required, except under "strict"
$opt_h = 0;
$opt_v = 0;

#these two declarations maybe modified by the Getopt::Std package.
#They are used here to cause a fall back to stdin and stdout
$opt_f = "&STDIN";
$opt_o = "&STDOUT";
$usage = "\nVersion: 1.0\nUsage: $0 [-f input_filename] [-o output_filename]
In the absense of one or both of the arguments, stdin or stdout will be substituted.\n\n";

getopts("f:o:vh");   #file_in, outfile, version, help

if ($opt_h || $opt_v)  #version and help print the same thing
{
    print STDERR $usage;
    exit;
}

open FILEIN, "<$opt_f" or die "Failed to open FILEIN";
open FILEOUT, ">$opt_o" or die "Failed to open FILEOUT";

while (<FILEIN>)
{
    print FILEOUT $_;       # a less capable cat(1)
}

close FILEIN;
close FILEOUT;

